name: Sync Code
on:
  workflow_dispatch: # Ручной запуск
  push:
    branches: [ "main" ] # Автозапуск при push в main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update from assistant" || echo "Нет изменений"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Используем ваш токен
