name: Sync Code
on:
  workflow_dispatch: # Запуск вручную
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update from assistant" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
