name: Sync Code
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Добавьте это!
    steps:
      - uses: actions/checkout@v4
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update" || echo "Нет изменений"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
